### ISSUE TITLE
qgis unable to run geographic detector

### ISSUE THREAD

**Issue by maverickyx** [gsnrguo/QGIS-Geographical-detector#3]
my qgis version is 3.32.1，when I finished gergraphic detector  installing，the qgis interface does not pop up and there is no response。I want to know why,thank you!

**Comment by gsnrguo** [comment]
Please download and install the latest version from the homepage of QGIS-geographical detector ([Geographical detector — QGIS Python Plugins Repository](https://plugins.qgis.org/plugins/geographical-detector/))
